[package]
name = "distraction-tracker"
version = "0.1.0"
edition = "2021"
authors = ["Drew Gotshalk"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.6.2", features = ["runtime-actix-rustls", "mysql"] }
actix-web = "4.3.0" 
actix-files = "0.6.2"
