services:
  mysql-stg:
    image: mysql:latest
    ports: 
      - 127.0.0.1:3306:3306
    volumes:
      - mysql_data_stg:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: dt_dev
      MYSQL_USER: dt-dev
      MYSQL_PASSWORD: dt_dev_pass
      
volumes:
  mysql_data_stg:
    driver: local
